### ISSUE TITLE
Wireframe Desktop v0

### ISSUE THREAD

**Issue by TitouanSans** [TitouanSans/Online-newspaper#1]
![Wireframe v0](https://user-images.githubusercontent.com/43538262/100746960-b6a72e80-33e1-11eb-8b61-afab115cb5b2.jpg)

**Comment by Herondil** [comment]
Il manque je pense les bords de l'écran, est-ce que tu peux rajouter un cadre qui l'indique ? 
Aussi, ce n'est pas précisé si on est sur tablette ou bureau.

**Comment by TitouanSans** [comment]
![Wireframe v0](https://user-images.githubusercontent.com/43538262/100749029-64b3d800-33e4-11eb-8c2d-952abe6d4a7e.jpg)

**Comment by TitouanSans** [comment]
![Wireframe smartphone v0](https://user-images.githubusercontent.com/43538262/100749340-d4c25e00-33e4-11eb-815f-103333ebd81b.jpg)
![Wireframe v0](https://user-images.githubusercontent.com/43538262/100749341-d55af480-33e4-11eb-9ce2-d7d160723a37.jpg)

**Comment by Herondil** [comment]
1) Où est la ligne de flottaison ? Est-ce qu'il y a du contenu à scroller ?

2) Il y a une petite marge entre l'alignement des catégories, du titre, et des articles, pourquoi ?

3) Le contenu n'est pas centré sur la page, est-ce un choix ?

**Comment by TitouanSans** [comment]
> 1. Où est la ligne de flottaison ? Est-ce qu'il y a du contenu à scroller ?
- En dessous des articles, au bord de l'écran. Ajout d'un icone pour indiquer s'il y a du contenu plus bas.

> 2. Il y a une petite marge entre l'alignement des catégories, du titre, et des articles, pourquoi ?
- Pas de raison, j'ai laissé cela comme ça. À voir si pertinent visuellement.

> 3. Le contenu n'est pas centré sur la page, est-ce un choix ?
- Je me demandais s'il y avais d'autres choses qui pouvaient être placé sur la page, j'ai laissé un espace au cas ou et ne l'ai pas comblé au final.

**Comment by Herondil** [comment]
>     * Pas de raison, j'ai laissé cela comme ça. À voir si pertinent visuellement.

Ce ne le sera pas si tu n'as pas une raison de le faire.

>     * Je me demandais s'il y avais d'autres choses qui pouvaient être placé sur la page, j'ai laissé un espace au cas ou et ne l'ai pas comblé au final.

Ok, dans ce cas il faut mieux aligner.

Sinon autre question, quand tu écris par exemple "ARTICLE 1", est-ce qu'il s'agit d'un texte ou d'une image ?

**Comment by TitouanSans** [comment]
Les articles sont juste des textes sur cette version.

**Comment by Herondil** [comment]
Ok, mais ma question porte sur le contenu des vignettes "ARTICLE", en voyant le wireframe, on ne sait pas ce qu'il va y avoir dedans.
