### ISSUE TITLE
WF Phone v1

### ISSUE THREAD

**Issue by TitouanSans** [TitouanSans/Online-newspaper#3]
![1-Smartphone-Pages](https://user-images.githubusercontent.com/43538262/100774782-c125f000-3402-11eb-80c7-01b1b8a503e5.png)

**Comment by Herondil** [comment]
Le wireframe semble coupé, c'est normal ?

**Comment by TitouanSans** [comment]
> Le wireframe semble coupé, c'est normal ?

- C'est la ligne de flottaison maladroitement illustrée.

**Comment by Herondil** [comment]
Ok je vois, il y a donc d'autres articles en dessous ? Il faudrait savoir combien, c'est important avant de commencer le code de savoir tout le contenu de la page en entier.

Pour la page du milieu, en haut on peut changer de catégorie c'est ça ? Je trouve ça un peu bizarre vu qu'il y a un autre "TITLE" en dessous.

**Comment by TitouanSans** [comment]
- D'accord je ferais un Wireframe de la totalité du site.

- Oui c'est ce qui va s'afficher en cliquant sur l'une des catégories. Pour l'étrangeté de la disposition ça ne me choque pas plus, par contre il manquerais peut-être un moyen de revenir à l'affichage original avec toutes les catégories, et je pourrais du coup changer la position du nom/logo du site "TITLE" et ajouter un texte indiquant, en plus du bouton sélectionner, la catégorie d'article active.

**Comment by Herondil** [comment]
Ok pour le second point, ça a l'air mieux en effet !
